#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_aws_code_deploy="0.0.1"
  jq -n --arg aws_code_deploy "$ver_aws_code_deploy" '{aws_code_deploy: $aws_code_deploy}'
}

version "$@"
